### ISSUE TITLE
Error with parsing some .epub and .pdf books.

### ISSUE THREAD

**Issue by BritishTeapot** [Acclorite/book-story#122]
**Where it happened?**
When trying to add some books, the app gives an error "Something went wrong." and refuses to ever try to add them again. Same books work fine in other readers (such as foliate on linux, and apple books).

**Short description of what is wrong**
Some books aren't added at all.

**Attach problematic file (necessary!)**
[books-error.zip](https://github.com/user-attachments/files/18146464/books-error.zip) (GitHub won't let me attach them uncompressed.)

**Screenshots (optional)**
![photo_2024-12-16_08-45-54](https://github.com/user-attachments/assets/77362b24-9966-4017-9717-f6a1199e9f0f)

**Comment by BritishTeapot** [comment]
Okay, just realized the Fichtengolc_tom1_rusky.pdf wasn't opening because it is just a bunch of images (so it can't be parsed). But other books still can't be opened.

**Comment by Acclorite** [comment]
**This issue was fixed in 0077241595999bc321b302fb80ebe7c5edd3bbfd**, although I've just fixed another issue, that was present in your EPUB files in 0d702f808fcb88d6cc840ed52313ae0b2bf27986.

Meanwhile, I've fixed all of your books until the next update (you should be able to add and read them correctly without any issues):
[fixed-books-#122.zip](https://github.com/user-attachments/files/18149476/fixed-books-.122.zip)

**Comment by BritishTeapot** [comment]
That was the fastest resopone and fix of my github issue I have ever seen.

You even the fixed the books 😍

Thank you so much ❤️

**Comment by Acclorite** [comment]
> You even the fixed the books 😍

"To Kill a Mockingbird" has a very weird issue with empty lines, currently inspecting.
