### ISSUE TITLE
Pagination in Reader

### ISSUE THREAD

**Issue by teemue** [Acclorite/book-story#13]
Please add an paginated layout to make it look more like an ordinary book :) Great work!

**Comment by Acclorite** [comment]
This might be very troublesome, considering current Reader system and progress tracking. Thank you for your idea, when I will finally have time and implement what's in my priority I will look into ways to do this. 

But right now I am full of work and have 20+ TODOs, and this feature will surely need me to rewrite a couple of thousands of lines. What I can say is that this feature most likely **will not be implemented in the near feature**. 

Sorry and if you have more ideas, feel free to create new Issues. Although I have lots of ideas, another couple of them won't harm, will they?

**Comment by Acclorite** [comment]
### Suggestions needed.

> This might be very troublesome, considering current Reader system and progress tracking.

Would I know that the "troublesome" part is not even close to progress tracking.

To create "paged" layout I need to split text into pages, separating paragraphs when they overflow and here's the first problem: **There is no way of doing that not manually, at least I don't know one**. Splitting pages would mean calculating how much paragraphs one page may take, then split one paragraph in two if it overflows (cannot fit).

**What does that mean?**
I need to process sometimes enormous amount of text, split it, and, of course, reprocess it when config changes (e.g. text size increases).

**What is the problem with that?**
It takes a lot of RAM and time to process, if we actually move aside implementation (which is the main problem).

I checked a lot of readers past days, sadly, there seems to be no Jetpack Compose Readers with Paged layout. The ones who gave me good idea is **FBReader** and **Readera**, which I think both have a great paged layout, but Closed Source / XML as it seems.

Let's start with **FBReader**, it gave me really good idea about using LazyColumn with ugly, but kinda working **scroll by exactly one screen height, to imitate "pages"**. Simple example:

```
            val text = remember { /* just List<String> here as text */ state.value.text }
            // List state to scroll by one screen
            val lazyListState = rememberLazyListState()
            val scope = rememberCoroutineScope()

            val screenHeightWithInsets = with(LocalDensity.current) {
                LocalConfiguration.current.screenHeightDp.dp.toPx() + // Screen height
                        WindowInsets.systemBars.getTop(this) + // System bars
                        WindowInsets.systemBars.getBottom(this)
            }

            LazyColumn(
                Modifier
                    .fillMaxSize()
                    .padding(horizontal = 24.dp, vertical = 36.dp),
                state = lazyListState,
                userScrollEnabled = false
            ) {
                itemsIndexed(
                    text,
                    key = { index, _ -> index }
                ) { _, paragraph ->
                    // Test Text
                    Text(
                        text = paragraph,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    // Some space between paragraphs
                    Spacer(modifier = Modifier.height(24.dp))
                }
            }
            
            // Box to create "tap zones"
            Box(modifier = Modifier.fillMaxSize()) {
                Box(modifier = Modifier
                    .fillMaxHeight()
                    .fillMaxWidth(0.3f)
                    .clickable {
                        scope.launch {
                            lazyListState.scrollBy(-screenHeightWithInsets)
                        }
                    }
                )
                Box(modifier = Modifier
                    .align(Alignment.CenterEnd)
                    .fillMaxHeight()
                    .fillMaxWidth(0.3f)
                    .clickable {
                        scope.launch {
                            lazyListState.scrollBy(screenHeightWithInsets)
                        }
                    }
                )
            }
```

This works kinda good, moves you to the next "page" by scrolling exactly one screen further/backward, except bottom and top lines can be cut. Problem is to efficiently hide/move overflown text.

Second example is **Readera**. I think it has great paged layout, it processes text super fast, correctly cuts overflown lines. This time I tried to use HorizontalPager, which, of course looks much better, but creates much more problems. I will not include here an example, as it is complicated and even less performant, but you can look at [StackOverflow question](https://stackoverflow.com/a/78282183), which is where I got "idea" about implementation.

Problem is to correctly measure, cut and process overflown text, ensure performance and make it **not-take-10-fucking-minutes-to-process**.

### What I propose
_Of course, I thought about some ways of making it at least close to paged layout.. And here is what I came up with:_

Using the first example, but letting user freely scroll up and down. Essentially it is not "paged" layout, but more like convenient tap zones and gestures to scroll exactly by one screen height, imitating "pages". Also provide top and bottom margin support as side feature, for better readability when using only (at least as much as possible) paged layout.
- **Pluses** 
   - Freedom to user, can both scroll and go to the next page with gestures/taps.
   - Large amount of possible customization: Different tap zones, gestures, combinations, maybe "page" switching effects.
   - Does not impact performance nor loading time. Simply as fast as current reader is (which is not really, but I can improve that).
   - No problems with progress tracking. Progress will work exactly the same.
- **Minuses**
   - Does not fully cover "paged" layout.
   - No separation into pages. Brings less customization to variants of showing text (like pages/free scroll option)
   - Cuts words at the top and the bottom. User scroll up/down may be needed after going to the next page to see full text.

In the end, what I propose is more page like gestures/tap zones for Reader, not Pagination.


### How can you help?
What I need is possible different solutions, workarounds or ideas. I would really appreciate a fresh look on this topic, maybe your eyes will tell you more than mine do. If you know matching libraries / projects, where this layout was implemented (Jetpack Compose!) this will also help. I know this feature is really important as for Reader and I'd say crucial, that's why I want to do at least **something**.

**Comment by Acclorite** [comment]
Also, I think it would be easier to understand if showing with an example, so here's my proposal's expected gestures behavior.
 
[Gestures](https://github.com/user-attachments/assets/f019e04d-4709-4196-96a7-34f1fc3f99b4)

**Comment by nNoidea** [comment]
> Please add an paginated layout to make it look more like an ordinary book :) Great work!

I like this idea mainly due to how easy it is to accidentally scroll in scroll mode.

**Comment by Acclorite** [comment]
**Did not** find doable solution.
As of now, replacement: #127

**Comment by Acclorite** [comment]
> Rather than looking at exclusively readers, what about other apps? Terminal apps such as [Termux](https://termux.dev/en/) and Android 15 QPR2's built in terminal display text line by line and "scroll" by shifting all lines up uniformly. The comparison isn't exact, since ebooks display text in a wildly different fashion, but it may be a starting point for you.
> 
> I've programmed a lot of things, but never an Android app, so I trust you when you say it's difficult.
> 
> Another ebook reader you can look for a solution from might be [Librera Reader](https://github.com/foobnix/LibreraReader), if you haven't tried already. If all else fails, you can try to contact the developers of the proprietary apps and see if they would be willing to share some code with you!

Thank you for suggestions, but all of these seem to use different library for "layouts" (not sure if it is correct way to put it, XML vs Jetpack Compose), and the way the Reader works in my app seem to quite differ from most I've seen, so I need a custom solution. I have ideas, I even tested some and they gave promising results, but it's not **only** about this.

We can take an example of Images(#69). It may seem like one feature, but I had to rework most of the code related to reading books to make it work. Same with this one, it might require some preparations.

**Comment by Acclorite** [comment]
Thank you!

> I haven't myself done exhaustive research, but there is [one that gave me an idea](https://github.com/yukuku/androidbible). The way that one works is by splitting the book into pages where each page contains a single chapter, and you have vertical scrolling for each page. Even if that doesn't solve your pagination problem, it would still be a cool feature for your app.

I have this feature planned.

> It gave me an idea that may not only solve your pagination problem, but also solve https://github.com/Acclorite/book-story/issues/186#issuecomment-2725360394: Instead of calculating the exact number of paragraphs that fit on a page and cutting off overflow paragraphs, simply do a dirty calculation for "about how many paragraphs fit on a page", and allow the user to scroll a little bit to read the overflow. It doesn't do an exact page turning mode, but it's close. (If this was confusing I can try to clarify it)

It varies. One paragraph may fit, but may as well 10. It still requires calculation. And I wouldn't really call this a solution..

> Anyways, as for some apps to look at, take a look at these:
https://www.openapk.net/category/religion/
https://flutterawesome.com/tag/bible/
https://flutterawesome.com/tag/book/
https://flutterawesome.com/tag/books/
https://github.com/eliranwong/DartBible-Flutter (unable to install)
https://github.com/dander11/flutter-bible (haven't tried installing)

Sadly none of these seem to use Jetpack Compose for UI, which is exactly the problem as the solution should be written in Compose.

**Comment by dphaldes** [comment]
Maybe this helps, https://gitlab.com/coolreader-ng/lxreader (it's available on F-Droid)
From my limited testing of the app, the pages work well

**Comment by scarylizard** [comment]
Episteme has implemented this functionality, and it seems to use Jetpack Compose.

https://github.com/Aryan-Raj3112/episteme

**Comment by a913cb82** [comment]
Issues I can see with the current horizontal scroll are:
1. Scroll by <100% makes it hard to track where the end of the previous page is after scrolling
2. Scroll by 100% often leads to a partially vertically cropped line at the top, requiring manual adjustment
3. Enabled vertical scrolling (necessary due to (2)) can disturb the "book" feeling

(1) seems less important, scrolling by 100% is the important case to optimize UX for.
(3) planned / done https://github.com/Acclorite/book-story/issues/186
(2) could be to addressed by auto-adjusting after a horizontal scroll to ensure the top line is fully visible. Here's an untested git diff to illustrate the idea

```
diff --git a/app/src/main/java/ua/acclorite/book_story/ui/reader/ReaderHorizontalGesture.kt b/app/src/main/java/ua/acclorite/book_story/ui/reader/ReaderHorizontalGesture.kt
index 295a91fb..ca81c863 100644
--- a/app/src/main/java/ua/acclorite/book_story/ui/reader/ReaderHorizontalGesture.kt
+++ b/app/src/main/java/ua/acclorite/book_story/ui/reader/ReaderHorizontalGesture.kt
@@ -51,15 +51,48 @@ fun Modifier.readerHorizontalGesture(
         mutableFloatStateOf(0f)
     }
 
+    suspend fun adjustScroll() {
+        val firstVisibleItem = listState.layoutInfo.visibleItemsInfo.firstOrNull() ?: return
+        val textIndex = firstVisibleItem.index // In Compose LazyList, .index accurately reflects list index
+        val offset = listState.firstVisibleItemScrollOffset
+        val lineHeightPx = with(density) { lineHeight.toPx() }
+        val paragraphHeightPx = with(density) { paragraphHeight.toPx() }
+
+        // The spacer is only placed on items where index > 0 per SpacedItem
+        val spacerHeight = if (textIndex > 0) paragraphHeightPx else 0f
+
+        val adjustment = if (offset < spacerHeight) {
+            // Unconditionally scroll up cleanly to the top of the item boundary if we land in the spacer
+            -offset.toFloat()
+        } else {
+            val textOffset = offset - spacerHeight
+            val remainder = textOffset % lineHeightPx
+
+            // Unconditionally scroll up by the remainder to fully reveal the cut line
+            if (remainder > 0f) {
+                -remainder
+            } else {
+                0f
+            }
+        }
+
+        if (abs(adjustment) > 0.5f) {
+            // Scroll by a negative amount moves the viewport up (pushing items down)
+            listState.scrollBy(adjustment)
+        }
+    }
+
     fun scrollBackward() {
         scope.launch {
             listState.scrollBy(-screenHeight.floatValue)
+            adjustScroll()
         }
     }
 
     fun scrollForward() {
         scope.launch {
             listState.scrollBy(screenHeight.floatValue)
+            adjustScroll()
         }
     }
 ```
