### ISSUE TITLE
Chapters in Reader

### ISSUE THREAD

**Issue by uniquePWD** [Acclorite/book-story#17]
There should be an easy way to jump anywhere in a book.

**Comment by Acclorite** [comment]
If you bring bottom and top bar, you have slider, moving it you can easily jump anywhere.
If you mean something different, please care to explain in **details**.

**Comment by uniquePWD** [comment]
> If you bring bottom and top bar, you have slider, moving it you can easily jump anywhere. If you mean something different, please care to explain in **details**.

I loaded a book into Books Story, I know I was on chapter 879. I have no idea what percentage that is, but I know the chapter. The slider isn't really helpful as it requires learning a new way to mark progress and different devices and screen sizes get in the way of something like percentage.

**Comment by Acclorite** [comment]
Look.
Percentage is calculated relatively and it does not matter whether your screen size is small or big.
Exact scroll index & offset are saved. Basically, if you change your screen size, the progress should remain the same - you will see exact paragraph on the top of the screen. In simple words, screen size does not matter for percentage.

I understand what you are trying to say, having some kind of bind towards chapter, but as of now reader is basically parsed TXT file, which then loads at the exact percentage. This thing always works as expected because even if you delete book's file, your text will remain as it is saved in app's internal storage at the stage of adding a book.

For now I can say that this is quite complicated topic, many things will be needed to be done and rewritten. I added this to my TODO, but as of now it is Frozen. Thanks for the explanation.

**Comment by Acclorite** [comment]
**Implemented.**
Wait for the next release.
Works good for most books, only EPUB.

Here's a little pic:
![Chapter example](https://github.com/user-attachments/assets/2b5d9fac-135b-4d6f-9c48-71f6041daeea)
