### ISSUE TITLE
Issues in identifying and showing books

### ISSUE THREAD

**Issue by biscuitwithtea** [Acclorite/book-story#31]
![IMG_20240810_163350](https://github.com/user-attachments/assets/1ff1f193-b2de-4fd4-8054-4c205223a0f4)

![IMG_20240810_163517](https://github.com/user-attachments/assets/bf7cced3-4175-4a94-a27d-fe683507743c)

![IMG_20240810_163633](https://github.com/user-attachments/assets/a6b98477-158d-481c-917f-623d53da749a)

Texts in Arabic shows words incorrectly : the order of letters in each word is replaced

**Comment by Acclorite** [comment]
Thanks for report.

**Let's start with the order of words. I cannot fix that, as you use LTR layout (English language), which means you see text from Left-To-Right.**

Solutions:

1. Force RTL layout for your app, you can do this in Developer Settings on your phone (see: [How to force RTL layout](https://www.phonearena.com/news/How-to-force-right-to-left-RTL-layouts-on-Android_id64154))
2. Add RTL locale to the app (Arabic as an example), so all text is displayed Right-To-Left. Right now I am planning to add localization platform, I would be glad if you could help translating the app later!

**Now about "This file is empty or corrupted".** 

This happens, because parser could not get any text from the book (some books are just buggy and text cannot be extracted). I have no fix to that, I will try to look into parser, maybe some issues with filtering out or identifying Arabic..

**Comment by halawnss** [comment]
I'll gladly help translating the app into Arabic 

Forcing RTL layout didn't work , and converting to txt made it this way :

![IMG_20240810_192824](https://github.com/user-attachments/assets/f126b7fb-dd2b-42a7-a2dc-4d0a253ecf9b)
![IMG_20240810_192835](https://github.com/user-attachments/assets/77d3e6e8-1540-495c-b4b3-0fb9a4bdd032)

**Comment by Acclorite** [comment]
Then probably invalid file. If even after converting - with another software, then it's not an issue on my side. TXT files are read as is, which excludes formation errors.

**Comment by Acclorite** [comment]
Please provide the file with error, so I can look for myself.

**Comment by halawnss** [comment]
[طوق_الحمامة_في_الأُلفَةِ_والأُلَّاف.txt](https://github.com/user-attachments/files/16575613/_._._._.txt)

**Comment by Acclorite** [comment]
And the one you couldn't add "pdf"

**Comment by halawnss** [comment]
[اميوليت_متجر_الساحرة_مانديليب_،_ابراهام_ميريت.pdf](https://github.com/user-attachments/files/16575785/_._._._._._.pdf)

There are many , but here is one of them

**Comment by Acclorite** [comment]
**TXT file that you provided is invalid.
PDF file cannot be extracted correctly.**
Converting PDF to TXT is very hard itself, but in Arabic, it is almost impossible.

I was able to successfully add and open Arabic books in EPUB, TXT.
Please, if you can, use EPUB(though maybe you will need to wait for the new update, as I greatly increased compatibility, see: #42). It is much better for text extracting.

PDF itself is not created for extracting, I spent weeks trying to do extract text correctly, and it still has issues I can't fix. Most if not all Readers load PDF directly, while I extract text from it.

Also, the app will soon be available for translation on Weblate, I would be grateful if you could translate it.
Sorry for inconvenience, the most I can suggest to you is use EPUB.

**Comment by biscuitwithtea** [comment]
It's okay
As for translation, I can for sure help if it can be done on mobile

**Comment by biscuitwithtea** [comment]
It's okay
I'll gladly help translating the app

**Comment by biscuitwithtea** [comment]
epub worked well

**Comment by Acclorite** [comment]
> I'll gladly help translating the app

Hey, the app is now pending approval for Libre plan on [Weblate](https://hosted.weblate.org/projects/book-story/book-story-translation/). If you want, you can request new language and start translation. Thank you.
