### ISSUE TITLE
Display PDFs as such, with pagination and fonts

### ISSUE THREAD

**Issue by CelianGdfrd** [Acclorite/book-story#59]
**Why you want this feature to be implemented? Please describe.**
Following up with my idea of displaying EPUBs within pages (duplicate of https://github.com/Acclorite/book-story/issues/13), I'd really like to see PDF documents displayed as such. MuPDF Viewer does this well for example, but I consider ebooks that come with a PDF version, and I'd like to add them all on my Book's Story library.

**Describe the feature you'd like to be implemented**
Don't change the PDF format to make it match EPUB display : just show the PDF as they were created, with their included fonts, the pagination, the formatting...

**Comment by CelianGdfrd** [comment]
(I'd also like to make a request for stylet annotation support on PDF, and being able to save them as new PDFs, but maybe that's premature to suggest it now)

**Comment by Acclorite** [comment]
> I'd really like to see PDF documents displayed as such.

That is not possible as of now, and does not match the idea of the app. This app offers you as much customizability as you would ever want.

> Don't change the PDF format to make it match EPUB display : just show the PDF as they were created, with their included fonts, the pagination, the formatting...

Displaying PDFs as is, means cutting off that customization, changing the whole system (as it extracts text and in the end you basically have no file formats at the library stage).

> Following up with my idea of displaying EPUBs within pages

The app is not separating into file formats. Every function works for every file format and will be (of course, considering it is possible, like extracting cover from TXT is not). The only thing that differs is parser logic, which extracts all it can, then adds it to the database.

> MuPDF Viewer does this well for example

This app is not really Document Viewer, but highly customizable eBook reader.

> and I'd like to add them all on my Book's Story library.

But what's wrong now? It does extract text.. Even if it is kinda bad, it still does. Although, I highly recommend using EPUB or TXT since **Release v1.2.0**, PDF is not a good format for extracting anything from it.

> (I'd also like to make a request for stylet annotation support on PDF, and being able to save them as new PDFs, but maybe that's premature to suggest it now)

There is no way I will step on PDF route once more.. I spent weeks trying to get it "working", it is terrible format.

Also, I am currently implementing #13, paged layout will be implemented and supported for all file formats.

For more info you can read: #24, #37

**Comment by CelianGdfrd** [comment]
Thank you for your answer, can't wait for #13 implementation !!!

**Comment by CelianGdfrd** [comment]
But then I've got a question that might be very, very stupid : 

Could there be a way to use Book Story as a "library manager", with the "Library" tab that is awesome, book images, reading progress and all, but then use another app to open and read the EPUB/PDF files ?

**Comment by Acclorite** [comment]
> then use another app to open and read the EPUB/PDF files ?

Probably not. This app is eBook reader, which includes managing, reading.

**I do not recommend** using PDF, really, use EPUB or TXT. Maybe in the future I will make a chooser on how to view PDFs as such, not now.

Right now I am developing new Reader features, which should extend what you can do.
