### ISSUE TITLE
Pure dark (OLED) setting does not use black color

### ISSUE THREAD

**Issue by nvllz** [Acclorite/book-story#64]
**Describe the bug**
"Pure dark (OLED)" setting does not use black (000000) color for the background.

**To Reproduce**
Go to Settings > Appearance and set "Pure dark (OLED)" to "Enabled".

**Expected behavior**
I expect the app to use HEX 000000 (black) as the background color when this setting is enabled. Otherwise, phrasing it "OLED" is misleading.

**Comment by Acclorite** [comment]
**Not a bug.** It does not exactly use **0x000000** because then the selected theme will not differ much.

Another thing is personally for me, as the owner of non-OLED screen, black color actually is quite eye straining, but I still like this black theme.

**So I have a good solution.** I will add "Absolute black" theme toggle when the OLED theme is enabled to change background color to **0x000000**. This will be the best way.

Thank you for the feature request.

**Comment by Acclorite** [comment]
**Added in 63bb317**, please wait for the next release.
When you enable "Absolute Dark" setting, background color changes to **0x000000**, which is completely black.
