### ISSUE TITLE
Disable copying the selection to the clipboard when sharing

### ISSUE THREAD

**Issue by nvllz** [Acclorite/book-story#67]
**Why you want this feature to be implemented? Please describe.**
I don't find auto-copying necessary.

**Describe the feature you'd like to be implemented**
When sharing a selection with an external translation/dictionary app, Book's Story copies the text to the clipboard. Unfortunately, I can't find an option to turn this off, and I find such a feature annoying. Would you mind adding a switch in the settings to control this?

**Comment by Acclorite** [comment]
> I don't find auto-copying necessary.

Well, I do. That is out of necessity, basically **I cannot even get selected text in Jetpack Compose**. So, to actually be able to use translator/dictionary I have to get that text and here comes workaround:

```
Copy & Save previous clipboard → Copy selected text (at least this is possible) in clipboard → Restore previous clipboard
```

It may be shown as new text has been copied, but actually it restores your old clipboard.

> and I find such a feature annoying

I find everything related to selection in Jetpack Compose annoying, but because of app's topic I have to work with it.

I pretty much described all I think about selection [here](https://github.com/Pool-Of-Tears/Myne/pull/204) and in #46.
Incorrect, closing.
